title: Página de estado de Inbound Latino
languageCode: es
params:
  copyrightHolder: Inbound Latino
  dateFormat: '2 de Enero, 2006 a las 3:04 PM'
  description_footer: >-
    <a class='text-grey-darkest' title='Visit example.com'
    href='https://inboundlatino.com/'>inboundlatino.com</a> Agencia de marketing
    digital.
  description_header: >-
    Información sobre la operación de los sistemas de<a
    class='text-grey-darkest' title='Visit example.com'
    href='https://inboundlatino.com/'>Inbound Latino</a>.<br />Síguenos <a
    class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>en Twitter</a> o subscribete a <a
    class='text-grey-darkest' href='%s' >RSS</a><br />para recibir las últimas
    novedades.
  eventsPerPage: 10
  logo: /images/clearstatus.svg
  meta_description: >-
    This status page provides updated information about our systems normal
    operation, incidents that may happen and their resolution.


    Esta página de estado te brinda información actualizada sobre la operación
    normal o incidentes que puedan ocurrir en nuestros sistemas. Además,
    notificarán sobre la resolución de los mismos.
  shortDateFormat: '15:04 — 2 Ene'
  systems:
    - description: Nuestro sitio web principal y blog
      link: 'https://inboundlatino.com/'
      name: Sitio Web
    - description: El sitio de auto-soporte de nuestra agencia
      link: 'https://ayuda.inboundlatino.com/'
      name: Centro de ayuda
    - description: Páginas para el seguimiento de proyectos.
      link: 'https://clientes.inboundlatino.com'
      name: Plataforma para clientes
  timezoneString: ' UTC'
